#ifndef ERROR_CODES_H
#define ERROR_CODES_H

# define SYNTAX_OK 0
# define SYNTAX_ERROR 2
# define BUILTIN_ERROR 2
# define SYNTAX_MISSING_TARGET 3

# define IS_A_DIRECTORY 126
# define PERMISSION_DENIED 126
# define COMMAND_NOT_FOUND 127

# define RESERVED_ERROR_CODES 128

#endif